runtime: python
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.12"
env: flex
entrypoint: streamlit run streamlit-app.py --server.port $PORT

automatic_scaling:
  max_num_instances: 1